services:
  # General Content
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Users" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.fos_group:
        class: AppBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Groups" }
        arguments:
            - ~
            - AppBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.fos_meeting:
        class: AppBundle\Admin\MeetingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Meeting" }
        arguments:
            - ~
            - AppBundle\Entity\Meeting
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true