<?php


namespace AppBundle\Form\Type;


use AppBundle\Entity\Feedback;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FeedbackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('attending', ChoiceType::class, [
                'label' => 'Was u aanwezig voor deze meeting?',
                'choices' => [
                    'Yes' => true,
                    'No' => false,
                    'Maybe' => true,
                ],
                'placeholder' => 'Aanwezigheid',
                'attr' => ['data-select'=>'true']
                ]
            )
            -> add('feedback', TextType::class, [
                'label' => 'Opmerkingen over deze meeting?',
                ])

            ->add('rating', RangeType::class, [
                'attr' => [
                    'min' => 1,
                    'max' => 10
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        return $resolver->setDefaults([
            'data_class' => Feedback::class,
        ]);
    }
}